server:
  port: 9000

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  web:
    resources:
      static-locations: /WEB-INF/static
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/assignment2
    username: postgres
    password: rmit
